# Generated by Django 6.0.2 on 2026-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageapp',
            name='token',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
